use df3_gse;
drop table if exists record;
create table record
(
    ID     integer auto_increment primary key,
    TS     datetime(6),
    FS     bigint,
    TI     bigint,
    STAT   tinyint,
    PDU_V  integer,
    DMY1   tinyint,
    BAT_V  integer,
    BAT_T  integer,
    SYS_T  integer,
    SYS_H  integer,
    SYS_P  integer,
    GND_P  integer,
    MOT_V  integer,
    DMY2   integer,
    MOT_T  integer,
    GEA_T  integer,
    MOT_R  integer,
    DMY3   integer,
    LIQ1_T integer,
    LIQ1_P integer,
    LIQ2_T integer,
    BOA_D  integer,
    GRA_X  integer,
    GRA_Y  integer,
    GRA_Z  integer,
    ACC_X  integer,
    ACC_Y  integer,
    ACC_Z  integer,
    ROT_X  integer,
    ROT_Y  integer,
    ROT_Z  integer,
    MAG_X  integer,
    MAG_Y  integer,
    MAG_Z  integer,
    CSUM   integer
)