
def get_element():
    return [
        {"label": "FS", "pos": 0, "len": 4, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "TI", "pos": 4, "len": 4, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "STAT", "pos": 8, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "PDU_V", "pos": 9, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "DMY1", "pos": 10, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "BAT_V", "pos": 11, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "BAT_T", "pos": 12, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "SYS_T", "pos": 13, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "SYS_H", "pos": 14, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "SYS_P", "pos": 15, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "GND_P", "pos": 16, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MOT_V", "pos": 18, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MOT_A", "pos": 19, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MOT_T", "pos": 20, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "GEA_T", "pos": 21, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MOT_R", "pos": 22, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "DMY3", "pos": 23, "len": 1, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "LIQ1_T", "pos": 24, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "LIQ1_P", "pos": 26, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "LIQ2_T", "pos": 28, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "BOA_D", "pos": 30, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "GRA_X", "pos": 32, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "GRA_Y", "pos": 34, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "GRA_Z", "pos": 36, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ACC_X", "pos": 38, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ACC_Y", "pos": 40, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ACC_Z", "pos": 42, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ROT_X", "pos": 44, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ROT_Y", "pos": 46, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "ROT_Z", "pos": 48, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MAX_X", "pos": 50, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MAX_Y", "pos": 52, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0},
        {"label": "MAX_Z", "pos": 54, "len": 2, "x": 1, "y": 1, "a": 1, "b": 0}
    ]
